spring:
  application:
    name: api-gateway

server:
  port: 1101

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka.didispace.com/eureka/
zuul:
  routes:
#  single-instance
    api-a:
      path: /eureka-client/**
      url: http://localhost:2001/
#  multi-instance
    api-b:
      path: /eureka-consumer/**
      serviceId: api-b

api-b:
  ribbon:
    listOfServers: http://localhost:2001/, http://localhost:2101/